### ISSUE TITLE
Bug: @types/estree type errors after upgrading ESLint to 9.20.0

### ISSUE THREAD

**Issue by Garfield550** [eslint/eslint#19418]
### Environment

Node version: v22.13.1
pnpm version: v10.2.1
Local ESLint version: v9.20.0
Global ESLint version:
Operating System: Darwin arm64 24.3.0

### What parser are you using?

@typescript-eslint/parser

### What did you do?

Updated from 9.19.0 to 9.20.0.

```js
The inferred type of 'default' cannot be named without a reference to
'.pnpm/@types+estree@1.0.6/node_modules/@types/estree'. This is likely not portable.
A type annotation is necessary.ts(2742)
```

### What did you expect to happen?

To compile like 9.19.0.

### What actually happened?

Open `packages/eslint-plugin-format/src/rules/test.ts`

<img width="784" alt="Image" src="https://github.com/user-attachments/assets/e32f900c-fc36-4c10-92d4-e2ccdcccaf78" />

### Link to Minimal Reproducible Example

https://github.com/Garfield550/eslint-9.20.0-estree-types-issue

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by fasttime** [comment]
Thanks for the bug report @Garfield550, I can reproduce the error when I install packages with pnpm. In ESLint v9.20.0, the type definition of `Rule.RuleModule` was changed to include a reference to the `ESTree` types (`ESTree.Node`):

https://github.com/eslint/eslint/blob/91d4d9f62095e302c71595cc04c47073f366315c/lib/types/index.d.ts#L552-L557

But somehow pnpm doesn't install the `@types/estree` package which is required by ESLint as a dependency:

https://github.com/eslint/eslint/blob/7e78b50dacc3faeacfb8c8dc6ad3359971395d1d/package.json#L112

And this results in the TypeScript compiler error you are seeing in the editor. I don't know why pnpm is behaving like this, we usually only test things with npm.

As a workaround, you could install the dependency manually in your `devDependencies` to get rid of the error with:

    pnpm i -D -w @types/estree

Or alternatively, you could create a `.npmrc` file in your project's directory with the line `node-linker=hoisted`, remove your `node_modules` directory and install again with pnpm. This is the same workaround as in #19419.

**Comment by arcanis** [comment]
I was curious so I dig a little more - I doubt the issue is that pnpm isn't installing `@types/estree`. This shows that the dependency is properly installed (`eslint` _has_ access to `@types/estree`):

```
node -p "require('module').createRequire(require.resolve('eslint')).resolve('@types/estree/package.json')"
```

More likely I think the issue is that when it generates the `.d.ts` file, TS needs to reference a type from `@types/estree`. When installing with npm, since `@types/estree` is hoisted to the top-level `node_modules`, TS isn't able to see that `@types/estree` is only accidentally made available to `eslint-plugin-format`. As a result, it doesn't show a warning.

When using pnpm however, since it enforces that packages can only require their own dependencies ([like modern package managers should](https://yarnpkg.com/advanced/rulebook#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies)), it doesn't hoist `@types/estree` to the top-level, and TS is then able to see the issue.

To fix that, I think `eslint-plugin-format` needs to declare the `@types/estree` dependency itself.

**Comment by nzakas** [comment]
Thanks @arcanis :pray: That makes sense. @antfu what do you think of the previous comment?

**Comment by remcohaszing** [comment]
This is not a problem with ESLint or pnpm. It’s a problem with the code. https://github.com/eslint/eslint/issues/19418#issuecomment-2649138341 is correct, but I suggest another fix.

The goal of this module is not to infer a shape that happens to satisfy the `Rule.RuleModule` constraint. The goal is to export an object whose type is `Rule.RuleModule`. The `satisfies` keyword has use cases, but it should be used sparsely. Instead, use a type annotation.

If you would manually write a type declaration for this file, you would probably write this:

```ts
import type { Rule } from 'eslint'

declare const rule: Rule

export default rule
```

But the code TypeScript source code would generate something like this:

```ts
import { Program } from 'estree'

declare const default_: {
  meta: {
    schema: []
  },
  create(context: Context): {
    Program(node: Program): void
  }
}

export default default_
```

The fix is to write the module as such:

```ts
import type { Rule } from 'eslint'

const rule: Rule = {
  meta: {
    // …
  },
  create(context) {
    // …
  }
}

export default rule
```

The only thing ESLint (or any library) could do to resolve it, is to remove any dependencies used for types.

**Comment by antfu** [comment]
For context, the `eslint-plugin-format` referenced in this issue is not mine https://github.com/antfu/eslint-plugin-format tho.

I see that ESLint deps `@types/estree` already, which seems to be correct. I feel this is more like a TypeScript detection/resolution issue. I think @remcohaszing's approach of explicitly typing the `Rule` object should be the best solution.

**Comment by Jack-Works** [comment]
The TypeScript error is telling you the type of this file cannot be properly named (used a type inside a transitive dependency), thus it is not portable, but since this file is a rule, that I expect the type of this file will not be exposed to the developer, it does not need to be portable. I agree that @remcohaszing's solution is good enough.

```ts
const rule: Rule.RuleModule = {}
export default rule
// or
const rule = {} satisfies Rule.RuleModule
export default rule as any
```

**Comment by bradzacher** [comment]
One other fix for this is that ESLint could (and should) export all 3rd party names that are publicly reachable from its types so that TS can generate `.d.ts` files without having to insert imports to other modules.

This can be as simple as adding
```ts
export { ESTree };
````
To this file: https://github.com/eslint/eslint/blob/91d4d9f62095e302c71595cc04c47073f366315c/lib%2Ftypes%2Findex.d.ts

---

What is happening here is that when TS generates a `.d.ts` file it **does not want to insert imports to any modules that are not already imported**. This is a rule it follows because modules can have type side-effects (eg via declaration merging) so if it adds an import where one wasn't previously it could change the meaning of code.

So instead it tries to generate the `.d.ts` file purely using the imported modules declared in the source file.

---

@remcohaszing is correct here in that people might think that for the code in the OP, TS would generate a `.d.ts` file that looks like this:

```ts
import type { Rule } from 'eslint';
declare const rule: Rule;
export default rule:
```

But this assumption is incorrect. Why? Because `satisfies` does not _override_ the type of an expression - instead it merely informs TS how to infer missing types. This means that instead TS will want to generate the following `.d.ts` file:

```ts
declare const _default: {
    meta: {
        schema: never[];
    };
    create(context: import("@eslint/core").RuleContext<{
        LangOptions: import("eslint").Linter.LanguageOptions;
        Code: import("eslint").SourceCode;
        RuleOptions: any[];
        Node: ESTree.Node;
        MessageIds: string;
    }>): {
        Program(node: ESTree.Program): void;
    };
};
export default _default;
```

[TS playground](https://www.typescriptlang.org/play/?isolatedModules=true#code/JYWwDg9gTgLgBDAnmApnA3gJQK4BsUC+cAZlBCHAEQoDOuwAdjJQNwBQbKAHpLHACYpiAQzzx0bOHBAoYwgFwZJUuDQDGACxQgFcANoBdADTKCJqWqgphMFAAo1EJtxgBKJSrhWY2KAw+ecAAKZADmUMIgdgwQgu4SgZ6OzlwwAHRWvDB2CYkqMYLmeVIyNDTCoSiKlABGEOSUynkEruyJZk1wBG1dJkTlMMA0xMC0cDj4aRMoALKxeCjsQA)

Important to note is how this result is broken - it references a namespace `ESTree` without importing it! This is the error OP is running into - TS is saying "the types I want to generate need this `ESTree` name but I don't know how to get that name without inserting an import to a new module". [^1]

So there are two fixes:
- as @remcohaszing mentioned - downstream users can use a type annotation on a variable to physically override the type, providing a more strict guarantee compared to `satisfies`.
- as I mentioned above - the eslint types can ensure that all names that it references in its exported types are referencable from its own package.

The first fix pushes the burden down to all users and forces them to write code to appease TS and pnpm.
The second fix centralises the burden with eslint itself so downstream consumers don't need to think about this class of problem.

Personally I'd vote for the latter.

[^1]: but wait - I hear you saying - the `.d.ts` file has an import that wasn't in the source code - it breaks the rule you mentioned! You're half right! [If you look at `eslint`'s types you'll see that the relevant module is actually declared in the `eslint` types](https://github.com/eslint/eslint/blob/91d4d9f62095e302c71595cc04c47073f366315c/lib%2Ftypes%2Findex.d.ts#L47-L63). So _technically_ TS both is and isn't violating it's rule there.

**Comment by nzakas** [comment]
> * as I mentioned above - the eslint types can ensure that all names that it references in its exported types are referencable from its own package.

We're still digging out of the mess that `@types/eslint` left for us. At the moment, the types we're exporting are still largely from that package with ongoing modifications to fix problems and improve compatibility with language plugins.

Is exporting `ESTree` dangerous if we are going to be moving all JS-related functionality to a separate package? Eventually, everything JS-related will be in the `@eslint/js` package, including all of the relevant types.

**Comment by remcohaszing** [comment]
I wouldn’t say a user _can_ use a type annotation. I would say a user _should_ use a type annotation. The `satisfies` keyword narrows the inferred type, but it doesn’t replace type annotations. The issue was reported here, but it could have been reported to any project that has a dependency on third party types. It’s not related to ESLint.

Having said that, it may be useful to re-export third party members, including types. But this is a different issue and I just don’t think this issue should be a reason to do it.

**Comment by bradzacher** [comment]
> Is exporting ESTree dangerous if we are going to be moving all JS-related functionality to a separate package? Eventually, everything JS-related will be in the @eslint/js package, including all of the relevant types.

No -- shouldn't be. Because it just forms part of that same API surface you're already exporting.
You already have an implicit API surface area dependency on the types -- this would just make it explicit.

When you eventually move all these types across -- you would similarly move the re-export across in the same (assumedly breaking) change.

---

As an example -- in typescript-eslint we've strived to re-export all relevant types so that our consumers never see such an issue when using our types or APIs. When flat configs released we had to make a lot of similar changes to this to our packages so that all types could be named properly. We didn't used to bother with it because plugins didn't need `.d.ts` files -- but flat configs changed the paradigm so now it's something we maintain as part of our API surface.

**Comment by remcohaszing** [comment]
A semi-related miscellaneous tip: Since ESLint supports JSX by default, replace `@types/estree` with `@types/estree-jsx`. This augments `@types/estree` with JSX node types and re-exports everything. It’s a drop-in replacement.

**Comment by nzakas** [comment]
Nice, thanks @remcohaszing :pray:

**Comment by fasttime** [comment]
If we export ESTree types from ESLint and users start referencing these types in their config files, we won't be able to remove the ESTree types later without a breaking change.

I think it would be better to alias the ESTree types we currently depend on with ESLint-specific names, e.g.:

```ts
type ESTreeNode = ESTree.Node;
```

and change the exported type definitions accordingly, for example:

```diff
type RuleModule = RuleDefinition<{
    LangOptions: Linter.LanguageOptions,
    Code: SourceCode,
    RuleOptions: any[],
    Visitor: NodeListener,
-   Node: ESTree.Node,
+   Node: ESTreeNode,
    MessageIds: string,
    ExtRuleDocs: {}
}>;
```

And then, when we decide to switch to core types, we could simply drop the `ESTree` import and provide a custom definition for `ESTreeNode` and others.

**Comment by JoshuaKGoldberg** [comment]
Is adding the types with a `@deprecated` tag an option? If it's being used as a transient helper, and should only exist so TypeScript can generate types, that could help prevent folks from relying on it. And IMO it isn't a breaking change to remove a deprecated type.

**Comment by nzakas** [comment]
@JoshuaKGoldberg do you mean we could do something like this?

```ts
/** @deprecated */
export { ESTree } from "@types/estree";
```

**Comment by nzakas** [comment]
Gotcha, thanks for the clarification.

I think I prefer @fasttime's approach as it reduces the surface area we're exposing through the API and thus also limits what might break when we remove the reference to `@types/estree`. We'd probably still want to mark it as deprecated to ensure people aren't relying on it outside of ESLint.

**Comment by fasttime** [comment]
We can try to fix this, I'm just not sure how the test should look like. It seems that we'll need some kind of integration test using pnpm to reproduce the original problem. Ideas?

**Comment by nzakas** [comment]
I'm not familiar enough with all of this to suggest anything else. Using pnpm in an integration tests seems reasonable. Maybe it could be part of the type integration tests?

**Comment by fasttime** [comment]
> I'm not familiar enough with all of this to suggest anything else. Using pnpm in an integration tests seems reasonable. Maybe it could be part of the type integration tests?

Yes, that would make sense. I think what we need for the integration test is a TypeScript project that has a dependency on `eslint` but not on `@types/estree`, such that it would be already broken under pnpm today. We could also create a custom test project. I'm going to mark to mark this as accepted in case someone wants to have a look.

**Comment by nzakas** [comment]
@snitin315 are you still working on this?

**Comment by snitin315** [comment]
Thanks for the ping, it slipped my attention. Yes, i'll pick this up next.

**Comment by fasttime** [comment]
@snitin315 just following up to ask if you're still planning to work on this? I can try to assist if necessary.

**Comment by snitin315** [comment]
@fasttime Sorry for the delayed response. It looks like this issue was resolved starting from `v9.23.0`. I’ve added a test case in https://github.com/eslint/eslint/pull/20507  to confirm the current behavior.

Steps to verify manually:

- Open: https://stackblitz.com/~/github.com/snitin315/pnpm-estree-types-issue

- Run `pnpm run test:types` — you should see the error with eslint v9.22.0

- Update the ESLint version to `9.23.0` in `package.json`

- Delete `node_modules` and `pnpm-lock.yaml`

- Run `pnpm install`

- Run `pnpm run test:types` again — there should be no errors now.

**Comment by fasttime** [comment]
Indeed TypeScript stopped reporting an error for the original repro in this issue starting with ESLint v9.23.0, precisely with [this commit](https://github.com/eslint/eslint/commit/0e20aa72fec53b16a21c42ac9e82969efa8f94d2) that updated the `Rule.RuleModule` type definition. But it seems that the same error still appears with other types that reference `ESTree.Node`. For example, this minimal snippet using `Scope.ScopeManager` still triggers the error with ESLint v10.0.0:

```ts
import type { Scope } from 'eslint';

export default {
  scopes: [],
  globalScope: null,
  acquire(node) {
    void node;
    return null;
  },
  getDeclaredVariables() {
    return [];
  },
  addGlobals() {},
} satisfies Scope.ScopeManager;
```

[**StackBlitz repro**](https://stackblitz.com/edit/eslint-issue-19418)

So I believe it would be still good to investigate solving this problem as discussed above, by replacing explicit usages of `ESTree` in the types.

**Comment by saberoueslati** [comment]
can this issue be assigned to me ?

I want to work on this,thank you
