### ISSUE TITLE
Ignore warning when file in linked folder

### ISSUE THREAD

**Issue by roadhump** [eslint/eslint#3720]
I have a linked folder in project. 

```
~/Projects/ttt tree -f
.
├── ./1.js
├── ./bzzz -> ../LINKED
└── ./xxx
    └── ./xxx/3.js

2 directories, 2 files
```

So, when I lint file in linked dir, I get an ignore warning

```
~/Projects/ttt eslint bzzz/2.js                
  eslint:cli Running on files +0ms
  eslint:cli-engine Processing /Users/roadhump/Projects/LINKED/2.js +5ms
  eslint:cli-engine Linting /Users/roadhump/Projects/LINKED/2.js +12ms
  eslint:config Constructing config for /Users/roadhump/Projects/LINKED/2.js +1ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Merging command line environment settings +1ms
  eslint:cli-engine Linting complete in: 28ms +12ms

/Users/roadhump/Projects/ttt/bzzz/2.js
  0:0  warning  File ignored because of your .eslintignore file. Use --no-ignore to override

✖ 1 problem (0 errors, 1 warning)

```

and if I run on folder, file is silently excluded

```
~/Projects/ttt eslint .
  eslint:cli Running on files +0ms
  eslint:cli-engine Processing /Users/roadhump/Projects/LINKED/2.js +101ms
  eslint:cli-engine Linting /Users/roadhump/Projects/LINKED/2.js +17ms
  eslint:config Constructing config for /Users/roadhump/Projects/LINKED/2.js +0ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Merging command line environment settings +2ms
  eslint:cli-engine Processing /Users/roadhump/Projects/ttt/1.js +12ms
  eslint:cli-engine Linting /Users/roadhump/Projects/ttt/1.js +14ms
  eslint:config Constructing config for /Users/roadhump/Projects/ttt/1.js +0ms
  eslint:config Using .eslintrc and package.json files +1ms
  eslint:config Loading /Users/roadhump/Projects/ttt/.eslintrc +0ms
  eslint:config Using /Users/roadhump/Projects/ttt/.eslintrc +22ms
  eslint:config Merging command line environment settings +0ms
  eslint:cli-engine Processing /Users/roadhump/Projects/ttt/xxx/3.js +12ms
  eslint:cli-engine Linting /Users/roadhump/Projects/ttt/xxx/3.js +12ms
  eslint:config Constructing config for /Users/roadhump/Projects/ttt/xxx/3.js +0ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Loading /Users/roadhump/Projects/ttt/.eslintrc +0ms
  eslint:config Using /Users/roadhump/Projects/ttt/.eslintrc +1ms
  eslint:config Merging command line environment settings +0ms
  eslint:cli-engine Linting complete in: 192ms +2ms

/Users/roadhump/Projects/ttt/1.js
  1:9  error  Strings must use doublequote  quotes

/Users/roadhump/Projects/ttt/xxx/3.js
  1:9  error  Strings must use doublequote  quotes

✖ 2 problems (2 errors, 0 warnings)


```

I think it would be nice if there were no difference between linked and real folders

**Comment by nzakas** [comment]
I'm not sure what you're reporting here...are you saying there's a bug? If so, what is it?

**Comment by roadhump** [comment]
Yes, I suppose it is a bug. First, it is very unexpected that I get ignore warning when file is not matched any `.eslintignore` patterns. And second, it is unexpected that symlinked folder is skipped when I run eslint on folder. 

In general there should be no difference between ESLint calls  

```
cd ProjectFolder
eslint normal_folder/file.js
eslint linked_folder/file.js
```

ESLint should use the same `.eslintrc` file here and lint files the same way. But now I get `0:0  warning  File ignored because of your .eslintignore file. Use --no-ignore to override` on the second call.

**Comment by BYK** [comment]
>First, it is very unexpected that I get ignore warning when file is not matched any .eslintignore patterns.

If you have shared your `.eslintignore` file and its location, we could have understood your viewpoint easier ;)

**Comment by roadhump** [comment]
@BYK  There is simply no `.eslintignore` at all

**Comment by BYK** [comment]
>@BYK There is simply no .eslintignore at all

Okay, this helps too :)

**Comment by BYK** [comment]
Glob documentation says the following:

>*follow* Follow symlinked directories when expanding ** patterns. Note that this can result in a lot of duplicate references in the presence of cyclic links.

@eslint/eslint-team what do you think? I fell like we should enable this.

**Comment by roadhump** [comment]
And by linked folder I mean `ln -s /some/other/location linked_folder`.

**Comment by nzakas** [comment]
@byk agree

**Comment by globexdesigns** [comment]
+1

Is this a difficult issue to fix? It has a pretty huge impact on projects which rely on symlinks. This also wasn't an issue in ESLint 1.3.x.

**Comment by BYK** [comment]
This is another side effect of switching to `node-glob` for file discovery. It should be just enabling an option but I'm not sure if it would break anything.

@globexdesigns - I can push a branch that has the fix and you can test that locally. Would that be okay?

**Comment by globexdesigns** [comment]
@BYK Sure, that would be great.

**Comment by BYK** [comment]
@globexdesigns https://github.com/eslint/eslint/tree/issue-3720

**Comment by globexdesigns** [comment]
@BYK No luck with that branch. Still seeing these warnings for all symlinked files:

```
0:0  warning  File ignored because of your .eslintignore file. Use --no-ignore to override
```

**Comment by BYK** [comment]
@globexdesigns thanks for checking. Will do some more research and update here.

**Comment by yourself-yourorg** [comment]
I am also seeing this error.

```
yourself@yourvm:~/projects/yourproject$ eslint --version
v1.5.0
yourself@yourvm:~/projects/yourproject$
yourself@yourvm:~/projects/yourproject$ lsb_release -d
Description:	Ubuntu 14.04.3 LTS
yourself@yourvm:~/projects/yourproject$
yourself@yourvm:~/projects/yourproject$ eslint packages/yourpackage/yourpackage-tests.js
The react/jsx-quotes rule is deprecated. Please use the jsx-quotes rule instead.

/home/yourself/projects/packages/yourself/yourpackage/yourpackage-tests.js
  3:14  error    Strings must use doublequote                  quotes
  3:25  warning  Missing function expression name              func-names
  3:33  error    Unexpected space before function parentheses  space-before-function-paren

/home/yourself/projects/yourproject/packages/yourpackage/yourpackage-tests.js
  0:0  warning  File ignored because of your .eslintignore file. Use --no-ignore to override

✖ 4 problems (2 errors, 2 warnings)

yourself@yourvm:~/projects/yourproject$
yourself@yourvm:~/projects/yourproject$ tree
.
├── LICENSE
├── packages
│   └── yourpackage -> /home/yourself/projects/packages/yourself/yourpackage
├── README.md
├── yourproject.css
├── yourproject.html
└── yourproject.js

3 directories, 7 files

yourself@yourvm:~/projects/yourproject$
yourself@yourvm:~/projects/yourproject$ sudo find / -name ".eslintignore"
yourself@yourvm:~/projects/yourproject$ 
```

**Comment by globexdesigns** [comment]
Another we can do to help fix this issue? It's quite distracting to see 1000s of false-positive warnings in our outputs.

**Comment by IanVS** [comment]
The issue is accepted, which means anyone is free to submit a PR to fix it.  Feel free to take a crack at it.

**Comment by szydan** [comment]
Maybe it would be easier to have a config property **ignoreSymlink** with default value true.
By default the warnings are printed as they are now.
The user can set it to false then there are no warnings but the linked files and folders are eslinted. 
The new property should be mention in documentation to make it clear that by default eslint will not follow  symlinks.

**Comment by marcstober** [comment]
Can't reproduce on 2.0.0-beta.3.

**Comment by nzakas** [comment]
Interesting, this might have been fixed with the ignore file rewrite. Can anyone else confirm?

**Comment by IanVS** [comment]
I also cannot reproduce this error on `2.2.0`.

@globexdesigns, are you still having problems with this?

**Comment by globexdesigns** [comment]
No. Seems to be okay now.

**Comment by adokania** [comment]
I am still seeing the same issue. Tried multiple different versions(2.2.0, 2.10.2, 1.0.0) of eslint. My eslintignore file includes the following:
`view_study/`

and i see the following warning when running eslint:

`/view_study/ignored_test.js
  0:0  warning  File ignored because of a matching ignore pattern. Use --no-ignore to override`

**Comment by IanVS** [comment]
@adokania, how did you invoke eslint?  Are you using symlinks?  From what I can tell, what you're experiencing seems to be unrelated to this issue.  Feel free to hop on our Gitter room if you'd like some help.
