### ISSUE TITLE
"YAMLException: Cannot read config file: .eslintrc" 

### ISSUE THREAD

**Issue by darkred** [eslint/eslint#5294]
(using `npm v3.3.12` in win10 x64)
Today I updated from v2.0.0 to `eslint v2.1.0`.

I have the following `.eslintrc` _(which I have generated using the new `--init` parameter)_ :
(located in `C:\Users\Kostas`)
```
module.exports = {
    "env": {
        "browser": true,
        "es6": true
    },
    "extends": "eslint:recommended",
    "rules": {
        "accessor-pairs": 2,
        "array-bracket-spacing": [
            2,
            "never"
        ],
        "array-callback-return": 2,
        "arrow-body-style": 2,
        "arrow-parens": 2,
        "arrow-spacing": 2,
        "block-scoped-var": 0,
        "block-spacing": 0,
        "brace-style": 0,
        "callback-return": 2,
        "camelcase": 0,
        "comma-spacing": 0,
        "comma-style": [
            2,
            "last"
        ],
        "complexity": 2,
        "computed-property-spacing": [
            2,
            "never"
        ],
        "consistent-return": 0,
        "consistent-this": 2,
        "curly": 2,
        "default-case": 2,
        "dot-location": [
            2,
            "property"
        ],
        "dot-notation": 2,
        "eol-last": 2,
        "eqeqeq": 0,
        "func-names": 0,
        "func-style": [
            2,
            "declaration"
        ],
        "generator-star-spacing": 2,
        "global-require": 2,
        "guard-for-in": 2,
        "handle-callback-err": 2,
        "id-blacklist": 2,
        "id-length": 0,
        "id-match": 2,
        "indent": 0,
        "init-declarations": 0,
        "jsx-quotes": 2,
        "key-spacing": 2,
        "keyword-spacing": [
            2,
            {
                "after": true,
                "before": true
            }
        ],
        "linebreak-style": [
            2,
            "unix"
        ],
        "lines-around-comment": 2,
        "max-depth": 0,
        "max-len": 0,
        "max-nested-callbacks": 2,
        "max-params": 2,
        "new-parens": 2,
        "newline-after-var": 0,
        "newline-per-chained-call": 0,
        "no-alert": 2,
        "no-array-constructor": 2,
        "no-bitwise": 2,
        "no-caller": 2,
        "no-catch-shadow": 2,
        "no-confusing-arrow": 2,
        "no-continue": 2,
        "no-div-regex": 2,
        "no-else-return": 2,
        "no-empty-function": 2,
        "no-eq-null": 2,
        "no-eval": 2,
        "no-extend-native": 0,
        "no-extra-bind": 2,
        "no-extra-label": 2,
        "no-extra-parens": 0,
        "no-floating-decimal": 2,
        "no-implicit-coercion": 2,
        "no-implicit-globals": 0,
        "no-implied-eval": 2,
        "no-inline-comments": 0,
        "no-inner-declarations": [
            2,
            "functions"
        ],
        "no-invalid-this": 2,
        "no-iterator": 2,
        "no-label-var": 2,
        "no-labels": 2,
        "no-lone-blocks": 2,
        "no-lonely-if": 0,
        "no-loop-func": 2,
        "no-magic-numbers": 0,
        "no-mixed-requires": 2,
        "no-multi-spaces": 0,
        "no-multi-str": 0,
        "no-multiple-empty-lines": 0,
        "no-native-reassign": 2,
        "no-negated-condition": 0,
        "no-nested-ternary": 2,
        "no-new": 2,
        "no-new-func": 2,
        "no-new-object": 2,
        "no-new-require": 2,
        "no-new-wrappers": 2,
        "no-octal-escape": 2,
        "no-param-reassign": 2,
        "no-path-concat": 2,
        "no-plusplus": 0,
        "no-process-env": 2,
        "no-process-exit": 2,
        "no-proto": 2,
        "no-restricted-imports": 2,
        "no-restricted-modules": 2,
        "no-restricted-syntax": 2,
        "no-return-assign": 2,
        "no-script-url": 2,
        "no-self-compare": 2,
        "no-sequences": 2,
        "no-shadow": [
            2,
            {
                "builtinGlobals": false,
                "hoist": "never"
            }
        ],
        "no-shadow-restricted-names": 2,
        "no-spaced-func": 2,
        "no-sync": 2,
        "no-ternary": 0,
        "no-throw-literal": 2,
        "no-trailing-spaces": 2,
        "no-undef-init": 2,
        "no-undefined": 2,
        "no-underscore-dangle": 2,
        "no-unmodified-loop-condition": 2,
        "no-unneeded-ternary": 2,
        "no-unused-expressions": 2,
        "no-use-before-define": 0,
        "no-useless-call": 2,
        "no-useless-concat": 0,
        "no-useless-constructor": 2,
        "no-var": 0,
        "no-void": 2,
        "no-warning-comments": 0,
        "no-whitespace-before-property": 2,
        "no-with": 2,
        "object-curly-spacing": [
            2,
            "never"
        ],
        "object-shorthand": 0,
        "one-var": 0,
        "one-var-declaration-per-line": [
            2,
            "initializations"
        ],
        "operator-assignment": [
            2,
            "always"
        ],
        "operator-linebreak": 0,
        "padded-blocks": 0,
        "prefer-arrow-callback": 0,
        "prefer-const": 0,
        "prefer-reflect": 0,
        "prefer-rest-params": 0,
        "prefer-spread": 0,
        "prefer-template": 0,
        "quote-props": 0,
        "quotes": 0,
        "radix": [
            2,
            "as-needed"
        ],
        "require-jsdoc": 0,
        "require-yield": 2,
        "semi": 2,
        "semi-spacing": [
            2,
            {
                "after": true,
                "before": false
            }
        ],
        "sort-imports": 2,
        "sort-vars": 2,
        "space-before-blocks": 0,
        "space-before-function-paren": 0,
        "space-in-parens": [
            2,
            "never"
        ],
        "space-infix-ops": 0,
        "space-unary-ops": 2,
        "spaced-comment": 0,
        "strict": [
            2,
            "never"
        ],
        "template-curly-spacing": 2,
        "valid-jsdoc": 2,
        "vars-on-top": 0,
        "wrap-iife": 2,
        "wrap-regex": 2,
        "yield-star-spacing": 2,
        "yoda": [
            2,
            "never"
        ]
    }
};
```

Here is what I get whenever I lint any file in command prompt:

```

C:\Users\Kostas\Desktop\1>eslint 1.js

C:\Users\Kostas\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:141
        throw e;
        ^
 YAMLException: Cannot read config file: C:\Users\Kostas\Desktop\1\.eslintrc
Error: end of the stream or a document separator is expected at line 2, column 10:
        "env": {
             ^
    at generateError (C:\Users\Kostas\AppData\Roaming\npm\node_modules\eslint\node_modules\js-yaml\lib\js-yaml\loader.js:162:10)
    at throwError (C:\Users\Kostas\AppData\Roaming\npm\node_modules\eslint\node_modules\js-yaml\lib\js-yaml\loader.js:168:9)
    at readDocument (C:\Users\Kostas\AppData\Roaming\npm\node_modules\eslint\node_modules\js-yaml\lib\js-yaml\loader.js:1508:5)
    at loadDocuments (C:\Users\Kostas\AppData\Roaming\npm\node_modules\eslint\node_modules\js-yaml\lib\js-yaml\loader.js:1544:5)
    at load (C:\Users\Kostas\AppData\Roaming\npm\node_modules\eslint\node_modules\js-yaml\lib\js-yaml\loader.js:1561:19)
    at Object.safeLoad (C:\Users\Kostas\AppData\Roaming\npm\node_modules\eslint\node_modules\js-yaml\lib\js-yaml\loader.js:1579:10)
    at loadLegacyConfigFile (C:\Users\Kostas\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:137:21)
    at loadConfigFile (C:\Users\Kostas\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:218:22)
    at Object.load (C:\Users\Kostas\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:435:18)
    at loadConfig (C:\Users\Kostas\AppData\Roaming\npm\node_modules\eslint\lib\config.js:67:33)
```

**Comment by nzakas** [comment]
If you want to use a JavaScript format for your configuration file, then you need to name it `.eslintrc.js`. 

You mentioned that you used `--init` to create this file, did you rename it or was it created this way?

(Also, there were some bugs in `--init` that we fixed in v2.1.0, so can you try upgrading to see if you can create a correct config?)


CC @IanVS

**Comment by darkred** [comment]
First of all, in case it was not apparent my OP: I use `.eslintrc` in my home folder for global settings.
That's why I have my `.eslintrc` in `C:\Users\Kostas`.
<br>

> If you want to use a JavaScript format for your configuration file, then you need to name it `.eslintrc.js`. 
> 
> You mentioned that you used `--init` to create this file, did you rename it or was it created this way?

Yes, I renamed it to omit the `.js` extension, but even after re-appending it, the issue remains.
i.e. I renamed the file located in `C:\Users\Kostas` from `.eslintrc` to `.eslintrc.js`
and I get the same error.


<br>
> (Also, there were some bugs in `--init` that we fixed in v2.1.0, so can you try upgrading to see if you can create a correct config?)

I have already tried `--init` against [this userscript](https://greasyfork.org/en/scripts/13169-firefox-for-desktop-list-fixed-bugs-in-mercurial) using this input: https://i.imgur.com/D0uUgkd.png.
I tried it again and the procuced `.eslintrc.js` is binary same to that produced previously, via v2.0.0.

**Comment by nzakas** [comment]
Okay, so this is not a problem with `--init`.

Can you run ESLint with the `--debug` flag and paste the output into this issue?

**Comment by darkred** [comment]
Yes, of course:

```

C:\Users\Kostas\Desktop\1>eslint --debug 1.js
  eslint:cli Running on files +0ms
  eslint:ignored-paths Looking for ignore file in C:\Users\Kostas\Desktop\1 +25ms
  eslint:ignored-paths Could not find ignore file in cwd +3ms
  eslint:cli-engine Processing C:\Users\Kostas\Desktop\1\1.js +2ms
  eslint:cli-engine Linting C:\Users\Kostas\Desktop\1\1.js +1ms
  eslint:config Constructing config for C:\Users\Kostas\Desktop\1\1.js +1ms
  eslint:config Using .eslintrc and package.json files +1ms
  eslint:config Loading C:\Users\Kostas\Desktop\1\.eslintrc.js +1ms
  eslint:config-file Loading JS config file: C:\Users\Kostas\Desktop\1\.eslintrc.js +1ms
  eslint:config-file Loading C:\Users\Kostas\AppData\Roaming\npm\node_modules\eslint\conf\eslint.json +158ms
  eslint:config-file Loading JSON config file: C:\Users\Kostas\AppData\Roaming\npm\node_modules\eslint\conf\eslint.json +1ms
  eslint:config Using C:\Users\Kostas\Desktop\1\.eslintrc.js +37ms
  eslint:config Merging command line environment settings +1ms
  eslint:config-ops Apply environment settings to config +0ms
  eslint:config-ops Creating config for environment browser +1ms
  eslint:config-ops Creating config for environment es6 +4ms
  eslint:cli-engine Linting complete in: 360ms +152ms

C:\Users\Kostas\Desktop\1\1.js
   42:1   error  '$' is not defined                            no-undef
   47:1   error  'GM_addStyle' is not defined                  no-undef
   50:1   error  'GM_addStyle' is not defined                  no-undef
   53:1   error  'GM_addStyle' is not defined                  no-undef
   56:1   error  'GM_addStyle' is not defined                  no-undef
   59:1   error  'GM_addStyle' is not defined                  no-undef
   62:1   error  'GM_addStyle' is not defined                  no-undef
   68:1   error  'GM_addStyle' is not defined                  no-undef
   95:1   error  '$' is not defined                            no-undef
  133:1   error  '$' is not defined                            no-undef
  135:3   error  '$' is not defined                            no-undef
  159:15  error  'moment' is not defined                       no-undef
  164:18  error  'jstz' is not defined                         no-undef
  221:3   error  '$' is not defined                            no-undef
  225:21  error  '$' is not defined                            no-undef
  228:9   error  Unexpected console statement                  no-console
  229:9   error  Unexpected console statement                  no-console
  231:9   error  Unexpected console statement                  no-console
  233:9   error  Unexpected console statement                  no-console
  248:11  error  Unexpected console statement                  no-console
  256:3   error  '$' is not defined                            no-undef
  256:16  error  '$' is not defined                            no-undef
  256:19  error  '$' is not defined                            no-undef
  258:26  error  '$' is not defined                            no-undef
  279:5   error  '$' is not defined                            no-undef
  283:5   error  '$' is not defined                            no-undef
  285:5   error  '$' is not defined                            no-undef
  286:7   error  '$' is not defined                            no-undef
  299:1   error  '$' is not defined                            no-undef
  302:18  error  's' is defined but never used                 no-unused-vars
  332:1   error  '$' is not defined                            no-undef
  382:9   error  '$' is not defined                            no-undef
  387:17  error  'sorting' is already defined                  no-redeclare
  388:13  error  '$' is not defined                            no-undef
  389:17  error  'mytable' is already defined                  no-redeclare
  390:22  error  'i' is already defined                        no-redeclare
  390:29  error  'j' is already defined                        no-redeclare
  392:30  error  'k' is already defined                        no-redeclare
  406:1   error  Function 'isRelevant' has a complexity of 17  complexity
  450:5   error  Unexpected console statement                  no-console
  456:5   error  Unexpected console statement                  no-console
  462:5   error  Unexpected console statement                  no-console
  467:1   error  '$' is not defined                            no-undef
  482:1   error  '$' is not defined                            no-undef

✖ 44 problems (44 errors, 0 warnings)
```

**Comment by darkred** [comment]
Here it is:

```

C:\Users\Kostas\Desktop\1>eslint --debug 1.js
  eslint:cli Running on files +0ms
  eslint:ignored-paths Looking for ignore file in C:\Users\Kostas\Desktop\1 +27ms
  eslint:ignored-paths Could not find ignore file in cwd +2ms
  eslint:cli-engine Processing C:\Users\Kostas\Desktop\1\1.js +3ms
  eslint:cli-engine Linting C:\Users\Kostas\Desktop\1\1.js +1ms
  eslint:config Constructing config for C:\Users\Kostas\Desktop\1\1.js +1ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Using personal config +2ms
  eslint:config-file Loading config file: C:\Users\Kostas\.eslintrc +1ms
  eslint:config-file Error reading YAML file: C:\Users\Kostas\.eslintrc +35ms

C:\Users\Kostas\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:141
        throw e;
        ^
 YAMLException: Cannot read config file: C:\Users\Kostas\.eslintrc
Error: end of the stream or a document separator is expected at line 2, column 10:
        "env": {
             ^
    at generateError (C:\Users\Kostas\AppData\Roaming\npm\node_modules\eslint\node_modules\js-yaml\lib\js-yaml\loader.js:162:10)
    at throwError (C:\Users\Kostas\AppData\Roaming\npm\node_modules\eslint\node_modules\js-yaml\lib\js-yaml\loader.js:168:9)
    at readDocument (C:\Users\Kostas\AppData\Roaming\npm\node_modules\eslint\node_modules\js-yaml\lib\js-yaml\loader.js:1508:5)
    at loadDocuments (C:\Users\Kostas\AppData\Roaming\npm\node_modules\eslint\node_modules\js-yaml\lib\js-yaml\loader.js:1544:5)
    at load (C:\Users\Kostas\AppData\Roaming\npm\node_modules\eslint\node_modules\js-yaml\lib\js-yaml\loader.js:1561:19)
    at Object.safeLoad (C:\Users\Kostas\AppData\Roaming\npm\node_modules\eslint\node_modules\js-yaml\lib\js-yaml\loader.js:1579:10)
    at loadLegacyConfigFile (C:\Users\Kostas\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:137:21)
    at loadConfigFile (C:\Users\Kostas\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:218:22)
    at Object.load (C:\Users\Kostas\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:435:18)
    at loadConfig (C:\Users\Kostas\AppData\Roaming\npm\node_modules\eslint\lib\config.js:67:33)

```

**Comment by xyyjk** [comment]
In v2.x version I also encountered the same problem, remove the rule 'no-eval' will be normal.

**Comment by nzakas** [comment]
@darkred can you rename your config file as .eslintrc.js and give me the output with `--debug`?

**Comment by darkred** [comment]
Yes. Here is the output with `--debug`: 
_(Now linting works ok, please see PS)_
```

C:\Users\Kostas\Desktop\1>eslint --debug 1.js
  eslint:cli Running on files +0ms
  eslint:ignored-paths Looking for ignore file in C:\Users\Kostas\Desktop\1 +27ms
  eslint:ignored-paths Could not find ignore file in cwd +3ms
  eslint:cli-engine Processing C:\Users\Kostas\Desktop\1\1.js +2ms
  eslint:cli-engine Linting C:\Users\Kostas\Desktop\1\1.js +1ms
  eslint:config Constructing config for C:\Users\Kostas\Desktop\1\1.js +1ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Using personal config +2ms
  eslint:config-file Loading JS config file: C:\Users\Kostas\.eslintrc.js +1ms
  eslint:config-file Loading C:\Users\Kostas\AppData\Roaming\npm\node_modules\eslint\conf\eslint.json +149ms
  eslint:config-file Loading JSON config file: C:\Users\Kostas\AppData\Roaming\npm\node_modules\eslint\conf\eslint.json +1ms
  eslint:config Merging command line environment settings +35ms
  eslint:config-ops Apply environment settings to config +1ms
  eslint:config-ops Creating config for environment browser +1ms
  eslint:config-ops Creating config for environment es6 +0ms
  eslint:cli-engine Linting complete in: 323ms +129ms

C:\Users\Kostas\Desktop\1\1.js
   42:1   error  '$' is not defined                            no-undef
   47:1   error  'GM_addStyle' is not defined                  no-undef
   50:1   error  'GM_addStyle' is not defined                  no-undef
   53:1   error  'GM_addStyle' is not defined                  no-undef
   56:1   error  'GM_addStyle' is not defined                  no-undef
   59:1   error  'GM_addStyle' is not defined                  no-undef
   62:1   error  'GM_addStyle' is not defined                  no-undef
   68:1   error  'GM_addStyle' is not defined                  no-undef
   95:1   error  '$' is not defined                            no-undef
  133:1   error  '$' is not defined                            no-undef
  135:3   error  '$' is not defined                            no-undef
  159:15  error  'moment' is not defined                       no-undef
  164:18  error  'jstz' is not defined                         no-undef
  221:3   error  '$' is not defined                            no-undef
  225:21  error  '$' is not defined                            no-undef
  228:9   error  Unexpected console statement                  no-console
  229:9   error  Unexpected console statement                  no-console
  231:9   error  Unexpected console statement                  no-console
  233:9   error  Unexpected console statement                  no-console
  248:11  error  Unexpected console statement                  no-console
  256:3   error  '$' is not defined                            no-undef
  256:16  error  '$' is not defined                            no-undef
  256:19  error  '$' is not defined                            no-undef
  258:26  error  '$' is not defined                            no-undef
  279:5   error  '$' is not defined                            no-undef
  283:5   error  '$' is not defined                            no-undef
  285:5   error  '$' is not defined                            no-undef
  286:7   error  '$' is not defined                            no-undef
  299:1   error  '$' is not defined                            no-undef
  302:18  error  's' is defined but never used                 no-unused-vars
  332:1   error  '$' is not defined                            no-undef
  382:9   error  '$' is not defined                            no-undef
  387:17  error  'sorting' is already defined                  no-redeclare
  388:13  error  '$' is not defined                            no-undef
  389:17  error  'mytable' is already defined                  no-redeclare
  390:22  error  'i' is already defined                        no-redeclare
  390:29  error  'j' is already defined                        no-redeclare
  392:30  error  'k' is already defined                        no-redeclare
  406:1   error  Function 'isRelevant' has a complexity of 17  complexity
  450:5   error  Unexpected console statement                  no-console
  456:5   error  Unexpected console statement                  no-console
  462:5   error  Unexpected console statement                  no-console
  467:1   error  '$' is not defined                            no-undef
  482:1   error  '$' is not defined                            no-undef

✖ 44 problems (44 errors, 0 warnings)
```



PS. Before renaming config file to .eslintrc.js , 
I had ran `npm install -g eslint` on top of my v2.1.0 installation 
and two files were updated (I didn't take note which)

**Comment by nzakas** [comment]
OK great, looks like the problem is solved.

**Comment by darkred** [comment]
Thanks for the replies

**Comment by pwang2** [comment]
the ghost issue bit me today. I tried re-name, re-edit, it still read an error edit which I put false in place of 0.

@darkred , could you explain how you are able to resolve it?
