### ISSUE TITLE
Separate exit code for error

### ISSUE THREAD

**Issue by Soullivaneuh** [eslint/eslint#9384]
**Tell us about your environment**

* **ESLint Version:** Any
* **Node Version:** 6
* **npm Version:** None, I use Yarn latest.

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

Not relevant.

**What did you do? Please include the actual source code causing the issue.**

Running an eslint instance which should crash (config error, intern failing like a permission issue...)

**What did you expect to happen?**

Having a different exist code issue.

**What actually happened? Please include the actual, raw output from ESLint.**

The exit code issue is the same as a well running eslint with rule violation detection.

Currently, eslint give the same exit code when some lint rules are not respected and when the binary is failing (example: When the provided configuration file does not exists).

On a automated script, we can't see the difference.

It would be great to have different exit codes:

* `1` For not respected lint rules.
* `2` When eslint is failing

Thanks.

**Comment by platinumazure** [comment]
I'm :+1: to this, but the team has been resistant to doing this on the grounds that it could be an unnecessarily painful breaking change.

I'm adding to the TSC agenda, but feel free to remove if enough people are :-1: on the issue.

**Comment by platinumazure** [comment]
**TSC Summary:** It is not desirable that an automated script cannot easily tell the difference between a lint failure and when ESLint itself fails for other reasons. Suggestion is to use different nonzero exit codes for those scenarios. However, in the past this has been identified as a painful change for users.

**TSC Question:** Could we consider adding this in a major release (i.e., for 5.0)?

**Comment by Soullivaneuh** [comment]
Thanks for your quick answer @platinumazure 

I don't really see how this change is painful for the users, but if it's the case, this could indeed be done on the next major.

IMHO, this is a must have and the different exit code system was already implemented on other tools like your. See an example here: https://github.com/FriendsOfPHP/PHP-CS-Fixer#exit-codes

Noob question: What is TSC? :stuck_out_tongue:

**Comment by Soullivaneuh** [comment]
Another example with [`yamllint`](https://github.com/adrienverge/yamllint):

```
$ yamllint app/config/config.yml 
app/config/config.yml
  1:1       warning  missing document start "---"  (document-start)
  2:8       error    too many spaces inside braces  (braces)
  2:33      error    too many spaces inside braces  (braces)
  3:8       error    too many spaces inside braces  (braces)
  3:31      error    too many spaces inside braces  (braces)
  4:8       error    too many spaces inside braces  (braces)
  4:29      error    too many spaces inside braces  (braces)
  5:8       error    too many spaces inside braces  (braces)
  5:37      error    too many spaces inside braces  (braces)
  6:8       error    too many spaces inside braces  (braces)
  6:42      error    too many spaces inside braces  (braces)
  7:8       error    too many spaces inside braces  (braces)
  7:31      error    too many spaces inside braces  (braces)
  8:8       error    too many spaces inside braces  (braces)
  8:28      error    too many spaces inside braces  (braces)
  8:31      warning  too few spaces before comment  (comments)
  9:8       error    too many spaces inside braces  (braces)
  9:28      error    too many spaces inside braces  (braces)
  9:31      warning  too few spaces before comment  (comments)
  10:8      error    too many spaces inside braces  (braces)
  10:26     error    too many spaces inside braces  (braces)
  19:6      warning  missing starting space in comment  (comments)
$ echo $?
1
$ yamllint 
usage: yamllint [-h] [-c CONFIG_FILE | -d CONFIG_DATA]
                [-f {parsable,standard}] [-s] [-v]
                FILE_OR_DIR [FILE_OR_DIR ...]
yamllint: error: too few arguments
$ echo $?
2
```

**Comment by not-an-aardvark** [comment]
Previous discussions: https://github.com/eslint/eslint/issues/1795, https://github.com/eslint/eslint/issues/2949

If we're distinguishing error codes we would also probably want to have a separate code for "ESLint unexpectedly crashed".

**Comment by Soullivaneuh** [comment]
> If we're distinguishing error codes we would also probably want to have a separate code for "ESLint unexpectedly crashed".

This is what I meant by "When eslint is failing", isn't it?

**Comment by not-an-aardvark** [comment]
I think there are three types of error scenarios here:

1. ESLint runs successfully, and reports linting problems.
1. ESLint fails to run due to user error (e.g. a missing configuration file)
1. ESLint fails to run due to an unexpected internal condition (e.g. a bug in a rule that causes an error to be thrown).

Since you gave a missing configuration file as an example, I'm assuming you are using "When eslint is failing" to refer to category 2. I'm saying that it might be worth distinguishing between expected failures caused by user error, and unexpected failures caused by potential bugs.

**Comment by ilyavolodin** [comment]
One more category: ESLint failed to parts your file at all. But in general I'm not sure I like this idea. CI assistance are usually setup once. Figuring out that config is missing should be part of that initial setup. If config file was there at the beginning, but missing after a while, then it's an hour that should break the build and somebody needs to look into it (or maybe the build isn't setup properly). Can you explain the scenario when this change might be useful? Also, could you update initial post to use our change request template?

P.S. TSC stands for Technical Steering Committee, and any core change has to be approved by it.

**Comment by Soullivaneuh** [comment]
> Can you explain the scenario when this change might be useful?

Simple: I'm writing a script that's will tell if the code on a specific branch is good or not after a push, on a web interface.

Currently, if eslint is failing, I can't see the difference and my script will just tell the code is wrong. It will be a false positive issue.

At this time, this is the only linter I found not returning a different exit code.

> Also, could you update initial post to use our change request template?

Done.

**Comment by platinumazure** [comment]
I'm :+1: for having as many exit codes as we need for different scenarios. And I think it would be good to clarify when changing or adding an exit code should be semver-minor vs semver-major and allow ourselves to make changes when we really need to.

@ilyavolodin You note that CI is usually set up once and then forgotten. By the same token, if we made a change to exit codes (hopefully with semver-major release), CI would only need to be tweaked once, and then forgotten once again. I think this team overestimates the pain of dealing with exit code changes (as long as we don't do so frequently and we do so under the correct type of semver release).

**Comment by ilyavolodin** [comment]
@platinumazure I wasn't referring to the pain of switching exit codes, I'm just not sure I understand the reasoning behind it. A build failure is a build failure and somebody should look at it. To me, it really doesn't matter if the build failed due to code issue, or due to config missing. But maybe it's just me, not sure.

**Comment by platinumazure** [comment]
Well, suppose there's some custom handling for actually reporting the CI
error. Maybe that would depend on an exit code for whether to message the
developer about their code being bad, or the IT group about an environment
issue. Much easier to do that by reading an exit code (the only other
option at that point is to read stdout/stderr). Hope that helps!

**Comment by ilyavolodin** [comment]
Very well, I'm still not sure that making a breaking change for something like this is justified, but I'm not going to oppose it (as part of major release, and 1 should stay a general error reported by ESLint rules for consistency).

**Comment by not-an-aardvark** [comment]
The TSC did not reach consensus on this issue in [today's meeting](https://gitter.im/eslint/tsc-meetings/archives/2017/10/12), so I'm leaving it on the agenda for next meeting.

**Comment by ilyavolodin** [comment]
We have a few people (including myself) who don't feel like this is important enough to include in the core, but don't feel strongly against it, and will not block the vote. As such, we would like input from other member of the TSC. @nzakas @alberto and @gyandeeps what are your feeling about this feature?

**Comment by Soullivaneuh** [comment]
> Well, suppose there's some custom handling for actually reporting the CI
error. Maybe that would depend on an exit code for whether to message the
developer about their code being bad, or the IT group about an environment
issue.

Exactly and for my personal use case: I'm writing a SaaS service which run some lint tools like yours and will get the lint report output.

Currently, because I can't make the difference between exit codes, I can't see if the lint was failing or not and will just get an output parsing error if the tool failed.

**Comment by alberto** [comment]
I say 👍

**Comment by nzakas** [comment]
Traditionally, we have decided against multiple exit codes because there hasn't been a lot of evidence that multiple exit codes provide enough value to risk breaking existing integrations that might have logic looking only for exit code 1 (like `if (exitCode != 1)`). My opinion has generally been the same as Ilya's in that if something the lint fails for any reason, then you need to look at it, so it only matters that the exit code isn't zero. 

As a reminder, we had an ill-fated experiment where we (actually me) changed the exit code to be the number of lint errors. We had to roll that back because it broke a lot of things, especially when the number of problems was > 254. That's part of why we've been so reluctant to change exit codes since then. 

That said, I can see an argument for making this change as the output for limiting problems vs. a crash is different, and I can see it being helpful for tools to be able to know how to bubble up the error details. 

So I'm :+1: for keeping exit code 1 for linting errors and introducing exit code 2 for any other type of errors. That would be a breaking change and would have to go in on a major release. I wouldn't want separate exit codes for every type of error condition as I think that's overkill.

**Comment by Soullivaneuh** [comment]
@nzakas It's a great news! :+1: 

> That would be a breaking change and would have to go in on a major release.

Maybe we can propose this change as an option for current stable to keep BC and then remove the option on next major?

**Comment by platinumazure** [comment]
> Maybe we can propose this change as an option for current stable to keep BC and then remove the option on next major?

I would be okay with that, but I'm not sure if this would require separate TSC discussion to approve adding a CLI option.

@eslint/eslint-tsc Any thoughts on creating an option that would change exit codes for users who want to opt in (releasing that as semver-minor), and then changing the default exit code behavior and removing the option in 5.0? Does that need another TSC motion given that we've already accepted the breaking change in 5.0?

**Comment by ilyavolodin** [comment]
I would be against doing that. Introducing an option now just to remove it in a few month doesn't seem like a good idea. I understand @Soullivaneuh desire to have a working solution now, but it feels like it's a lot more work for us to do that (introduce a new option, retire a new option, move the code around, etc.).
