### ISSUE TITLE
Log Which Configuration File is Being Used

### ISSUE THREAD

**Issue by Rabadash8820** [eslint/eslint#9959]
**Tell us about your environment**
Windows 10 64-bit
gulp-eslint 4.0.2

* **ESLint Version:** 4.17.0 (dependency of `gulp-eslint`)
* **Node Version:** 6.11.4
* **npm Version:** 5.6.0

**What did you do?**
Accidentally named my configuration file `eslintrc.yml` (without the dot) while working with the `gulp-eslint` Gulp task.

**What happened?**
Configuration file was not recognized by ESLint, and therefore it fell back to the `.eslintrc` in my Users/ directory.  That file had a bunch of rules/settings that I did *not* want, leading to an hour or two of trying to figure out why Gulp/NPM were giving me errors about modules that I wasn't even trying to use (particularly ones for working with React).

**What did you expect to happen?**
Now that I know what my mistake was, this is what I would expect to happen.  However, it made me wonder if periods should really be required at the start of a config file's name.  I know that the `.*rc` syntax is pretty universal among dev tools, and I know that supporting additional config file names is a pain, however, I can think of the following reasons to support "period-less" config file names:

1. Prevent newbish mistakes like mine.  If someone accidentally named an `eslintrc.*` file without the leading period, I think it's still pretty clear what they meant, so why fall back to the home directory one and cause confusion?  Sure, you could extend this argument to support every slight misspelling of `eslintrc`, but I think the period case is a particular gotcha.
2. There is a precedent for config files without leading periods in other dev tools, e.g., `gulpfile.js`, `webpack.config.js`, global `npmrc` files, and `nuget.config`.
3. Files with leading periods are hidden on Windows systems by default, and cannot be created with "New > Text document".  I certainly pity the dev who hasn't dealt with and gotten around these limitations before, but for *real* newbs this could be another source of confusion.

I suppose I could've brought these arguments up to any open-source tool with a `.*rc` file, but ESLint just happened to be the first one that caused me some grief. 😛

**Comment by not-an-aardvark** [comment]
I feel like this isn't specific to the `.` character before the config file name -- it could have just as easily occurred if you typed in something like `.esilntrc` by mistake.

It seems like it would be better to not keep a config file in your home directory, so that an error gets reported faster in this case.

**Comment by Rabadash8820** [comment]
@not-an-aardvark I wasn't aware that there was a config file in my home directory until this occurred, I'm not sure if it got added by `gulp-eslint` or what.  I did acknowledge that supporting "typo" filenames is kind of a slippery slope, but speaking from experience, the period is harder to catch.

**Comment by mysticatea** [comment]
> cannot be created with "New > Text document".

You can. `.foo.` becomes `.foo`.

**Comment by Rabadash8820** [comment]
@mysticatea  didn't know that one.  I usually `echo. > .foo`.  Anyway I'm getting the vibe that we don't think this is a necessary change?

**Comment by not-an-aardvark** [comment]
I personally feel like this isn't necessary, although I'm not opposed to it if other team members are in favor of it.

(In either case, I thanks for opening up an issue! I feel like there are definitely some usability improvements that we could make for the general issue of a config not being found.)

**Comment by ljharb** [comment]
This would be a breaking change. I don't personally see the value in it; as https://github.com/eslint/eslint/issues/9959#issuecomment-364324495 points out, it wouldn't actually solve the problem of "typos" - so I'm not sure what the point would be.

**Comment by Rabadash8820** [comment]
@ljharb I did some poking around earlier, and it looks like there is an array called [CONFIG_FILES](https://github.com/eslint/eslint/blob/bf3d4943aa583f042c315e640ef90018d016f2c2/lib/config/config-file.js#L46) in config-file.js that stores the valid names of config files, and in what order they should be searched for in a given directory.  Couldnt the period-less names just be slapped on the end of that array?  The only way I can see this being a breaking change is if a user already has a period-less config file floating around their project's directory hierarchy that they don't know about.

**Comment by ljharb** [comment]
That's exactly why it would be a breaking change.

Separately, I think it would be inappropriate for a default config file not to have a leading dot (package.json is special).

**Comment by Rabadash8820** [comment]
Well that's really the discussion I was interested in having. Given the examples above of other tools that *don't* have config file names with leading dots, why do you feel that a lack of dot is "inappropriate"?  That's a pretty strong word to use, so I'm sure there's a good reason, but the only reason I can see for today's prevalence of the `.*rc` naming convention is just that--convention.  Is there some history behind it?

**Comment by ljharb** [comment]
As far as I know, npmrc files are always `.npmrc`, including global ones.

Dotfiles are "hidden", conceptually, and config files generally fall into the same bucket - things that are present, but not interacted with in day-to-day operation. Separately, "convention" is enough of a reason on its own - it trumps virtually everything else.

**Comment by Rabadash8820** [comment]
This was my [source](https://docs.npmjs.com/files/npmrc#files) for the `npmrc` example.  I still had 3 other examples though.  I get the sense that "code over configuration" files like `gulpfile.js` and `webpack.config.js` sort of fall into a category of their own; it's these declarative JSON/YAML config files that usually use the `.rc` convention.  Microsoft has almost used XML-based configs though (e.g., `app.config`, `web.config`, the aforementioned `nuget.config`) without leading dots, and even their modern .NET Core stuff uses names like `appsettings.json`.

So I guess my point is, if leading dot vs no leading dot is just a completely arbitrary convention (that, like so many other things, seems to be different in Microsoft-land than everywhere else), then why not support both? It's really no different than supporting `.eslintrc.yaml` and `.eslint.yml`.

**Comment by not-an-aardvark** [comment]
In general, I don't think it's good design to have two different ways to do the exact same thing, unless there is a significant advantage to having two different ways. In this case it seems like there isn't much of a benefit, so I don't think it's worth it.

Along similar lines, we don't read files called `.eslintConfigFile.yml` by default either -- I think it's reasonable to ask users to give their files a particular name.

**Comment by Rabadash8820** [comment]
@not-an-aardvark That's a good point.  Tis a fine line between supporting multiple user preferences, and having "different ways to do the exact same thing".  I can't really think of a significant *advantage* for supporting period-less config file names, I'm just offering one user story where it would've been helpful.  As I said above, when someone creates a file called `eslintrc`, it's pretty clear what they mean, and that leading dot is almost as hard to catch as a whitespace error when you forget it, certainly harder than, say, swapping two letters.  And I didn't even think to look at the file path when the errors I was getting suggested that a config file was still in effect.  Seems like being lenient on the dot would help some and hurt none (or at least very few, as the breaking scenario that I described above seems like a heck of an edge case).

**Comment by platinumazure** [comment]
Personally, I would love to see a change where a home directory ESLint is not used (either by default in a semver-major release, or behind a CLI option in a semver-minor), and then users could use the flag and get the ESLint "config file was not found" error. I think that could help clue users in that the config they created was not actually read, possibly due to having the wrong file name.

That said, there's probably more to this.

**Comment by Rabadash8820** [comment]
@platinumazure  I like that idea.  I've really never understood why so many tools (git, npm, etc.) have to have a million config files scattered about... one in the project, one in home, one in Program Files, etc.  Another (not mutually exclusive) option that would only be a semver-minor bump would be to warn the user if any file names with "almost" config names are encountered anywhere in the directory hierarchy, and tell them which config file we are falling back to.  This would be similar to git's behavior when, for example, you type `git checkot` (without the "u"), and it says 

```
git: 'checkot' is not a git command. See 'git --help'.

The most similar command is
        checkout
```

A possible ESLint-config warning might look like this:

```
Warning: Did you mean for file 'C:\my-project\eslintrc.yml` to be an ESLint configuration file?
Valid config file names are:
    {Contents of CONFIG_FILES array}

Falling back to config file 'C:\Users\user\.eslintrc'
```

As far as implementation goes, there could be an array similar to that [`CONFIG_FILES`](https://github.com/eslint/eslint/blob/bf3d4943aa583f042c315e640ef90018d016f2c2/lib/config/config-file.js#L46) one that I mentioned above, perhaps called `TYPO_CONFIG_FILES`, where any file with one of those names would raise the warning.  A more sophisticated approach might be to have some kind of string similarity algorithm to catch typos...idk how Git does it.

In either case, using the `--no-eslintrc` or `--config` command-line options would prevent this warning.

**Comment by Rabadash8820** [comment]
@not-an-aardvark @platinumazure
Any thoughts on my above idea for an incorrect config filename/fallback warning?  If it's worth further consideration then we should probably also rename this issue, as I'm not talking specifically about leading-period names anymore... and I feel like that's what people are giving thumbs down for.

**Comment by not-an-aardvark** [comment]
I'm not opposed to the idea, although I'm also not sure it would be worth the additional complexity because I don't think it's very common for people to have a config file with the wrong name. With git, users type out a command every time they use it, so typos are likely over time. However, with ESLint, users would typically create a config file once and then they wouldn't need to deal with the name again.

**Comment by Rabadash8820** [comment]
So perhaps the best compromise is just to output which config file is being used?  This requires no additional validation checks but lets users know when a config file other than the one that they intended is being used.  The message could be as simple as:

`Using config file C:\path\to\.eslintrc\` or
`No config file found`

Using the `--no-eslintrc`, `--config`, or `--quiet` flags would hide this message.

**Comment by not-an-aardvark** [comment]
I don't think it would be a good idea to print out a message like that every time a config file is found. It could interfere with tools that read the output of ESLint with a machine-readable formatter, and I think it would also be very noisy to have that kind of message appear every time you lint something.

I think we already provide some information about which configs were resolved when the `--debug` flag is used.

**Comment by Rabadash8820** [comment]
Okay, I had not used the `--debug` option before, and it does indeed show which config file is used.  However, I still don't think the use case of this issue has been resolved, namely, a user who is completely new to ESLint (like I was/am).  That user has little to no knowledge of the CLI flags (including `--debug`), little to no knowledge of configuration options or plugins, and they just forgot the leading dot in their `.eslintrc` file.  Even if I had used `--debug`, I would've still been sidetracked for an hour by this message:

```
Oops! Something went wrong! :(

ESLint: 4.17.0.
ESLint couldn't find the plugin "eslint-plugin-react". This can happen for a couple different reasons:
```

Eventually, I might have scanned the following couple lines:

```
2018-02-16T17:14:26.058Z eslint:config Constructing config file hierarchy for C:\SupplyTech\VoiceApps\Alexa\AlexaStars\lambda\src
2018-02-16T17:14:26.058Z eslint:config Using .eslintrc and package.json files
2018-02-16T17:14:26.059Z eslint:config Loading C:\SupplyTech\VoiceApps\Alexa\AlexaStars\lambda\package.json
2018-02-16T17:14:26.060Z eslint:config-file Loading package.json config file: C:\SupplyTech\VoiceApps\Alexa\AlexaStars\lambda\package.json
2018-02-16T17:14:26.060Z eslint:config-file Loading JSON config file: C:\SupplyTech\VoiceApps\Alexa\AlexaStars\lambda\package.json
2018-02-16T17:14:26.061Z eslint:config Using personal config file
2018-02-16T17:14:26.063Z eslint:config Using personal config
2018-02-16T17:14:26.064Z eslint:config-file Loading config file: C:\Users\vicareld\.eslintrc
```

That last line, as you mentioned, does at least show the real problem, but I think it's too easily lost in the surrounding noise.  So here is a different compromise: **only output a message about which config file is being used when that config file is *outside* the current folder hierarchy**.  Both your and @platinumazure's earlier comments suggest that keeping config files in user/global locations is a bad practice anyway, so you might as well show a warning to that effect.  How does that sound?

**Comment by not-an-aardvark** [comment]
I don't think ESLint should emit status messages during the course of normal operation. A message like this would be noisy and not actionable, and I think it would result in poorer UX in the common case. Putting an `.eslintrc.*` file in a home directory is currently a fully supported use case, so I think we should assume that the user knows what they're doing rather than second-guessing them.

The current behavior is a tradeoff between usefulness and complexity -- people can take advantage of home-directory configs because they don't need to copy config files everywhere, but as you've seen, the complexity makes it harder for users to figure out why ESLint is doing a particular thing.

I think there are two ways to address this:

* We could decide that the current tradeoff is worthwhile, and leave the behavior as-is. To make things easier for new users, we could investigate providing a better way for users to debug their configuration. (I don't think emitting a status message on every linting run is a good solution, but it could be useful to have an opt-in way of doing this.)
* We could decide that the complexity cost outweighs the benefits, and remove the home-directory behavior. Note that this would have the additional cost of breaking a lot of peoples' workflows.

**Comment by Rabadash8820** [comment]
Breaking existing workflows is never good, so your first solution is certainly better in that respect.  I don't see an "opt-in way" to get status messages as being helpful in this case though, because again the new user has to *know* that they can and should opt in to debug their configuration.

I'm confused by your resistance to a status message.  I have only ever used ESLint in a Gulp task with `gulp-eslint` so I'm only familiar with its command line output in the context of other Gulp output.  From what I can tell, ESLint *does* emits status messages every time it finds lint, but emits nothing when all of the files are good; maybe that's what you mean by "normal operation"?  I just don't see adding a one-line message about the config file as being noisy, and it *would* be actionable to the user who realizes that that wasn't their intended config file.  Nor does it second-guess anyone's workflow; it's just a status message, not a warning.

That said, I agree that users who are used to no output when everything is good might find a new status message annoying; maybe they're who you were thinking of.  Those users can of course use the `--quiet`, `--config`, or `--no-eslintrc` flags, but that's extra typing than they're used to.  Perhaps, rather than a new CLI flag, their could be a new root setting in the `.eslintrc.*` file itself, such as `quiet: true`.  That way, users who are confident in their choice of global config file (or anyone really) can turn off that status message (and all other non-error messages?), and the option name is consistent with the CLI flag that they're probably already familiar with.

**Comment by not-an-aardvark** [comment]
To clarify, the status message would be actionable if the user has really made a configuration error. However, it would be not be actionable if the user is intentionally using a home-directory config -- it's just noise that needs to be suppressed.

The difference between linting errors and status messages is that linting errors are the primary output that users are looking for. The entire purpose of running ESLint is to see the linting results (and presumably address them). On the other hand, a message about a config file is tangential to what users are trying to do when they lint their files, and it would often be informing the user about something that they are already aware of.

As an analogy: imagine if the [`ls`](https://en.wikipedia.org/wiki/Ls) command-line tool showed an output like this:

```
$ ls
Note: not displaying dotfiles. Use `ls -a` if you want to see dotfiles.
foo/    bar/    baz.txt
```

This would be very annoying; it would create a lot of visual noise with a status message, when the user presumably just wanted to see a list of files. It might be useful to a small percentage of users, but in a majority of cases the message would just be an annoyance. Even if `ls` added an option (e.g. `ls --quiet`), to suppress the warning, it would still be annoying for users to have to enable the option.

This is called the Rule of Silence. [This article](http://www.linfo.org/rule_of_silence.html) has some good explanations for why it's desirable.

**Comment by Rabadash8820** [comment]
Hm, "Rule of Silence".  I love learning new jargon. 😛

Given your points, and that excellent article, I think I'm second-guessing the status message now...  However, ending the great discussion that's been happening on this issue with "meh, there's nothing we can do" doesn't seem very satisfactory.  We still have this issue of new users who use the wrong config file by accident but aren't made aware of it.

I'd like to revisit my [earlier suggestion](https://github.com/eslint/eslint/issues/9959#issuecomment-364501085) about checking for possible config file name typos.  I think it might have been my better idea, on the following grounds:

1. Everything about that warning is actionable.  It shows the incorrect file name that the user provided, shows the *correct* file names, and shows which config file we are falling back to, which would explain all subsequent errors.
2. The additional complexity is minimal.  My suggestion was to have an array of "typo" file names that get checked at each level of the directory hierarchy.  ESLint already iterates over the six file names in that CONFIG_FILES array at each level; I'm talking about adding maybe a dozen more iterations.  Compared to the time it takes to do ESLint's *actual* linting job, these additional checks won't be noticed at all, and they sound pretty easy to implement (I would even be willing to take a stab at a PR if no one else is interested).
3. Continuing the analogy with git... Yes, it makes more sense for git to check for misspelled commands at each invocation than for ESLint to check for misspelled config filenames at each invocation.  But that means that our beloved, and generally speedy, git is checking for typos at *each invocation* and we don't notice it, so it will be the same for ESLint.
4. As you said, it isn't "very common" for people to have a config file with the wrong name.  So the vast majority of users will not be bothered by the new warning.  The only ones who will see it will be newbs who need it, *or* users with misspelled config files floating around in their directory hierarchy, like I [described above](https://github.com/eslint/eslint/issues/9959#issuecomment-364340482).  @ljharb and I described this use case as a breaking change, but it really doesn't break anything, it's just a new warning.  And I would argue that a file called `.eslitnrc` or `eslintrc` floating around in someone's directory hierarchy is in all likelihood just a forgotten mistake, and we would be doing users a service by pointing out that cluttering file.

**Comment by not-an-aardvark** [comment]
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

**Comment by Rabadash8820** [comment]
@not-an-aardvark  The ball was in your court after my last comment.  I suggested a change and even offered to help implement it.  The only reason we haven't reached a consensus yet is because we _haven't reached a consensus yet_ and were still discussing.  However, if you're really going to close this issue, then I will move on with my life 😛

**Comment by not-an-aardvark** [comment]
As I mentioned in https://github.com/eslint/eslint/issues/9959#issuecomment-366158958, I'm not convinced that it's worth making a change here, and based on the lack of support for this issue from other team members, I concluded that there isn't a strong consensus in favor of changing this. In general, we've found that issues which don't reach consensus after several months rarely end up reaching consensus in the future, so I decided to close this issue. That doesn't mean it's a bad idea -- we just don't want to commit to adding it and maintaining it in the future.
